/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_gaomh_jni_Main */

#ifndef _Included_cn_gaomh_jni_Main
#define _Included_cn_gaomh_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_gaomh_jni_Main
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_gaomh_jni_Main_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_gaomh_jni_Main
 * Method:    getVersion
 * Signature: (CIZ)I
 */
JNIEXPORT jint JNICALL Java_cn_gaomh_jni_Main_getVersion
  (JNIEnv *, jclass, jchar, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
